services:
        adventure.form.type.newAdventure:
                class: Gwyath\Bundle\AdventureBundle\Form\Type\NewAdventureType
                tags:
                        - { name: form.type, alias: newAdventure }