<?php

namespace Gwyath\Bundle\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdventureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdventureRepository extends EntityRepository
{
}
