<?php

namespace Gwyath\Bundle\AdventureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTypeRepository extends EntityRepository
{
}
